### PR TITLE
XFG3 LSV

### PR DESCRIPTION
**Pull request by surtboy**
proxy for implementation of LSV described in XFG3

### CODE REVIEW

**Comment by mangrou** [comment]
hi, 

I can’t find your code under my account.

Can you put your codes under this link?
https://github.com/QuantLet/XFG3-Temp.git https://github.com/QuantLet/XFG3-Temp.git

## Thank you very much.

Meng-Jou Lu
Ladislaus von Bortkiewicz Chair of Statistics
School of Business and Economics
Humboldt-Universität zu Berlin
Spandauer Str. 1 R. 400
10178 Berlin
Email: lumengjo@cms.hu-berlin.de
Phone: +49 30 2093-5721
Fax:+49 30 2093-5649

**Comment by gstar1990** [comment]
Hi MJL, the first 7 folders in the list belongs to my code. The following is my screenshot fyi:

**Comment by gstar1990** [comment]
Hi MJL, the first 7 folders in the list belongs to my code. The following is my screenshot fyi:
[cid:ff968615-971c-4914-a275-e91a12806421]
Can you see the folders in the graph as well? Thank you.

Best,
Li

**Comment by surtboy** [comment]
Meng-Jou Lu，您好！ 

　　   I will try.  I am not familiar with Github, the process is:
1. I fork url https://github.com/QuantLet/XFG3-Temp.git
2. I push my code to url under my account
3. I create a pull request to you 

Is the proces above right?

BTW: I send you the wrong account "surfboy" by mistake, sorry

======== 2016-01-27 23:42:46 您在来信中写道： ========

hi, 

I can’t find your code under my account.

Can you put your codes under this link?
https://github.com/QuantLet/XFG3-Temp.git https://github.com/QuantLet/XFG3-Temp.git

## Thank you very much.

Meng-Jou Lu
Ladislaus von Bortkiewicz Chair of Statistics
School of Business and Economics
Humboldt-Universität zu Berlin
Spandauer Str. 1 R. 400
10178 Berlin
Email: lumengjo@cms.hu-berlin.de
Phone: +49 30 2093-5721
Fax:+49 30 2093-5649

> On Jan 26, 2016, at 3:40 PM, surtboy notifications@github.com wrote:
> 
> proxy for implementation of LSV described in XFG3
> 
> You can view, comment on, or merge this pull request online at:
> 
> https://github.com/mangrou/XFG3-Temp/pull/4 https://github.com/mangrou/XFG3-Temp/pull/4
> Commit Summary
> 
> XFG3-Temp
> XFG3LSV
> File Changes
> 
> A XFGLSV/Figure 4 Transition Probability.png https://github.com/mangrou/XFG3-Temp/pull/4/files#diff-0 (0)
> A XFGLSV/Figure3 LSV Leverage.png https://github.com/mangrou/XFG3-Temp/pull/4/files#diff-1 (0)
> A XFGLSV/Metainfo.txt https://github.com/mangrou/XFG3-Temp/pull/4/files#diff-2 (19)
> A XFGLSV/fdmhestondupirefwdop.cpp https://github.com/mangrou/XFG3-Temp/pull/4/files#diff-3 (278)
> A XFGLSV/fdmhestondupirefwdop.hpp https://github.com/mangrou/XFG3-Temp/pull/4/files#diff-4 (121)
> A XFGLSV/fdmhestondupireop.cpp https://github.com/mangrou/XFG3-Temp/pull/4/files#diff-5 (183)
> A XFGLSV/fdmhestondupireop.hpp https://github.com/mangrou/XFG3-Temp/pull/4/files#diff-6 (100)
> A XFGLSV/hestondupireprocess.cpp https://github.com/mangrou/XFG3-Temp/pull/4/files#diff-7 (125)
> A XFGLSV/hestondupireprocess.hpp https://github.com/mangrou/XFG3-Temp/pull/4/files#diff-8 (57)
> A XFGLSV/leveragesurface.hpp https://github.com/mangrou/XFG3-Temp/pull/4/files#diff-9 (30)
> A XFGLSV/modninepointlinearop.cpp https://github.com/mangrou/XFG3-Temp/pull/4/files#diff-10 (25)
> A XFGLSV/modninepointlinearop.hpp https://github.com/mangrou/XFG3-Temp/pull/4/files#diff-11 (43)
> A XFGLSV/modtriplebandlinearop.hpp https://github.com/mangrou/XFG3-Temp/pull/4/files#diff-12 (51)
> Patch Links:
> 
> https://github.com/mangrou/XFG3-Temp/pull/4.patch https://github.com/mangrou/XFG3-Temp/pull/4.patch
> https://github.com/mangrou/XFG3-Temp/pull/4.diff https://github.com/mangrou/XFG3-Temp/pull/4.diff
> —
> Reply to this email directly or view it on GitHub https://github.com/mangrou/XFG3-Temp/pull/4.

—
Reply to this email directly or view it on GitHub.

= = = = = = = = = = = = = = = = = = = = = = 
　　　　　　　　致
礼！

　　　　　　　　　　　　　　袁勋
　　　　　　　　　　　　　　yuanxun@ustc.edu
　　　　　　　　　　　　　　　2016-01-28

**Pull request merged**
